### ISSUE TITLE
Detected as Virus 

### ISSUE THREAD

**Issue by LordDunlow** [Guerra24/GameAwaiter#2] opened 2024-11-08 20:09 UTC
Windows Defender removes automatically as exe is detected as virus

**Comment by Guerra24** [comment] 2024-11-25 14:56
Hello!

ML (machine learning) based antivirus tends to detect some apps as viruses, and I can't really do anything about it.

Duplicate of #1

**Closed as completed by Guerra24** 2024-11-25 14:56 UTC
